/*========== User Section ============*/
// Sign in
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS'
export const SIGNIN_USER_FAIL = 'SIGNIN_USER_FAIL'
// Sign up
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL'
// General
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'

/*========== App Section ============*/
export const ADD_TO_NEWOBSERVATIONS_SUCCESS = 'ADD_TO_NEWOBSERVATIONS_SUCCESS';
export const ADD_TIME_AND_LOC_TO_NEWOBSERVATIONS_SUCCESS = 'ADD_TIME_AND_LOC_TO_NEWOBSERVATIONS_SUCCESS';
export const ADD_HUMANS_TO_NEWOBSERVATIONS_SUCCESS = 'ADD_HUMANS_TO_NEWOBSERVATIONS_SUCCESS';
export const ADD_ANIMALS_TO_NEWOBSERVATIONS_SUCCESS = 'ADD_ANIMALS_TO_NEWOBSERVATIONS_SUCCESS';
export const RETRIEVE_OBSERVATIONS_SUCCESS = 'RETRIEVE_OBSERVATIONS_SUCCESS'
export const RETRIEVE_NEW_OBSERVATIONS_SUCCESS = 'RETRIEVE_NEW_OBSERVATIONS_SUCCESS'
export const SET_STATUS = 'SET_STATUS'
export const SYNC_OBSERVATIONS_SUCCESS = 'SYNC_OBSERVATIONS_SUCCESS'

