export const RETRIEVE_ALL_COURSES_SUCCESS = 'RETRIEVE_ALL_COURSES_SUCCESS'
export const RETRIEVE_ALL_COURSES_FAIL = 'RETRIEVE_ALL_COURSES_FAIL'

export const RETRIEVE_MY_COURSES_SUCCESS = 'RETRIEVE_My_COURSES_SUCCESS'
export const RETRIEVE_MY_COURSES_FAIL = 'RETRIEVE_MY_COURSES_FAIL'

export const ADD_TO_NEWOBSERVATIONS_SUCCESS = 'ADD_TO_NEWOBSERVATIONS_SUCCESS';
export const ADD_TIME_AND_LOC_TO_NEWOBSERVATIONS_SUCCESS = 'ADD_TIME_AND_LOC_TO_NEWOBSERVATIONS_SUCCESS';
export const ADD_HUMANS_TO_NEWOBSERVATIONS_SUCCESS = 'ADD_HUMANS_TO_NEWOBSERVATIONS_SUCCESS';
export const ADD_ANIMALS_TO_NEWOBSERVATIONS_SUCCESS = 'ADD_ANIMALS_TO_NEWOBSERVATIONS_SUCCESS';
export const RETRIEVE_OBSERVATIONS_SUCCESS = 'RETRIEVE_OBSERVATIONS_SUCCESS'
export const SET_STATUS = 'SET_STATUS'


export const RETRIEVE_MOVIES_GENRES_SUCCESS = 'RETRIEVE_MOVIES_GENRES_SUCCESS';

export const RETRIEVE_POPULAR_MOVIES_SUCCESS = 'RETRIEVE_POPULAR_MOVIES_SUCCESS';
export const RETRIEVE_NOWPLAYING_MOVIES_SUCCESS = 'RETRIEVE_NOWPLAYING_MOVIES_SUCCESS';
export const RETRIEVE_MOVIES_LIST_SUCCESS = 'RETRIEVE_MOVIES_LIST_SUCCESS';
export const RETRIEVE_MOVIE_DETAILS_SUCCESS = 'RETRIEVE_MOVIE_DETAILS_SUCCESS';
export const RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS = 'RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS';


export const RETRIEVE_CATEGORIES_SUCCESS = 'RETRIEVE_CATEGORIES_SUCCESS'


/*========== User Section ============*/
// Sign in
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS'
export const SIGNIN_USER_FAIL = 'SIGNIN_USER_FAIL'
// Sign up
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL'
// General
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'

// Profile Edit
export const ADD_TO_FAVORITE_CATEGORIES_SUCCESS = 'ADD_TO_FAVORITE_CATEGORIES_SUCCESS'
export const REMOVE_FROM_FAVORITE_CATEGORIES_SUCCESS = 'REMOVE_FROM_FAVORITE_CATEGORIES_SUCCESS'

export const ADD_TO_MY_STORE_SUCCESS = 'ADD_TO_MY_STORE_SUCCESS'
export const REMOVE_FROM_MY_STORE_SUCCESS = 'REMOVE_FROM_MY_STORE_SUCCESS'

export const ADD_TO_CASUAL_WISHLIST_SUCCESS = 'ADD_TO_CASUAL_WISHLIST_SUCCESS'
export const REMOVE_FROM_CASUAL_WISHLIST_SUCCESS = 'REMOVE_FROM_CASUAL_WISHLIST_SUCCESS'


/*========== App Section ============*/
export const RETRIEVE_RECOMMENDED_OFFS_SUCCESS = 'RETRIEVE_RECOMMENDED_OFFS_SUCCESS'
export const RETRIEVE_POPULAR_OFFS_SUCCESS = 'RETRIEVE_POPULAR_OFFS_SUCCESS'
export const RETRIEVE_PRODUCT_DETAILS_SUCCESS = 'RETRIEVE_PRODUCT_DETAILS_SUCCESSS'
export const RETRIEVE_PRODUCTS_SEARCH_RESULT_SUCCESS = 'RETRIEVE_PRODUCTS_SEARCH_RESULT_SUCCESS'
export const RETRIEVE_CATEGORY_PRODUCTS_SUCCESS = 'RETRIEVE_CATEGORY_PRODUCTS_SUCCESS'
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST'
export const RETRIEVE_SIMILAR_PRODUCTS_SUCCESS = 'RETRIEVE_SIMILAR_PRODUCTS_SUCCESS'
export const RETRIEVE_OTHER_PRODUCTS_SUCCESS = 'RETRIEVE_OTHER_PRODUCTS_SUCCESS'

export const ADD_TO_NOTIFS = 'ADD_TO_NOTIFS'
//export const RETRIEVE_PRODUCT_DETAILS_SUCCESS = 'RETRIEVE_PRODUCT_DETAILS_SUCCESS'